CREATE TABLE IF NOT EXISTS `#__folio` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
	`title` VARCHAR(250) NOT NULL DEFAULT '' ,
	`alias` VARCHAR(255) NOT NULL DEFAULT '' , 
	PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci AUTO_INCREMENT=1;

