CREATE TABLE IF NOT EXISTS `#__folio` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
	`title` VARCHAR(250) NOT NULL DEFAULT '' ,
	`alias` VARCHAR(255) NOT NULL DEFAULT '' , 
	`catid` INT(11) NOT NULL DEFAULT '0',
	`state` TINYINT(1) NOT NULL default '0',
	`image` VARCHAR(255) NOT NULL,
	`company` VARCHAR(250) NOT NULL DEFAULT '',
	`phone` VARCHAR(12) NOT NULL DEFAULT '',
	`url` VARCHAR(255) NOT NULL,  
	`description` TEXT, 
	`publish_up` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`publish_down` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`ordering` INT(11) NOT NULL DEFAULT '0', 
	`checked_out` INT(11) NOT NULL DEFAULT '0',
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`access` INT(11) NOT NULL DEFAULT '1',
	`language` CHAR(7) NOT NULL DEFAULT '',
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` INT(10) unsigned NOT NULL DEFAULT '0',
	`created_by_alias` VARCHAR(255) NOT NULL DEFAULT '',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
	`featured` TINYINT(3) unsigned NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci AUTO_INCREMENT=1;

