CREATE TABLE IF NOT EXISTS `#__folio` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
	`title` VARCHAR(250) NOT NULL DEFAULT '' ,
	`alias` VARCHAR(255) NOT NULL DEFAULT '' , 
	`catid` INT(11) NOT NULL DEFAULT '0',
	`state` TINYINT(1) NOT NULL default '0',
	`image` VARCHAR(255) NOT NULL,
	`company` VARCHAR(250) NOT NULL DEFAULT '',
	`phone` VARCHAR(12) NOT NULL DEFAULT '',
	`url` VARCHAR(255) NOT NULL,  
	`description` TEXT, 
	`publish_up` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`publish_down` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`ordering` INT(11) NOT NULL DEFAULT '0', 
	PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci AUTO_INCREMENT=1;

